/**
 * apps/backend/src/db/queries/users.ts
 *
 * MAJOR FUNCTION: Repository for all `users` table SQL operations.
 * The rest of the app calls typed functions — no raw SQL outside this file.
 *
 * REPOSITORY PATTERN: Route handlers call findUserByEmail(), createUser() etc.
 * They never write SQL directly. Benefits:
 *   - SQL is in one place — easy to audit for injection risks
 *   - Query logic is separately testable (mock the pool, test the function)
 *   - Changing the DB schema only requires updating this file
 *
 * SQL INJECTION PREVENTION:
 *   ALL queries use parameterized placeholders ($1, $2, $3...).
 *   pg sends values separately over the wire as typed parameters.
 *   The DB never interprets values as SQL — injection is structurally impossible.
 *
 *   BAD  (injectable): `WHERE email = '${email}'`
 *   GOOD (safe):       `WHERE email = $1`, [email]
 */
import { pool } from '../client';

// ─── Row type matching the `users` table schema ───────────────────────────────
export interface UserRow {
  id: string; // UUID, generated by gen_random_uuid()
  email: string;
  username: string;
  password_hash: string | null; // bcrypt hash — never log or send this to the client; null for OAuth users
  created_at: Date;
}

/**
 * Find a user by email address.
 * Used by: POST /auth/login
 * Returns null if no user found — caller decides how to handle (401 vs 404).
 */
export async function findUserByEmail(email: string): Promise<UserRow | null> {
  const result = await pool.query<UserRow>(
    `SELECT id, email, username, password_hash, created_at
     FROM users
     WHERE email = $1
     LIMIT 1`,
    [email.toLowerCase().trim()] // Normalize email before comparison
  );
  return result.rows[0] ?? null;
}

/**
 * Find a user by their UUID.
 * Used by: socket reconnection to verify user still exists.
 */
export async function findUserById(id: string): Promise<UserRow | null> {
  const result = await pool.query<UserRow>(
    `SELECT id, email, username, password_hash, created_at
     FROM users
     WHERE id = $1`,
    [id]
  );
  return result.rows[0] ?? null;
}

/**
 * Create a new user row.
 * Called AFTER email uniqueness check in the route handler.
 * The DB-level UNIQUE(email) constraint is the final guard against races.
 *
 * RETURNING clause: PostgreSQL returns the inserted row immediately.
 * Avoids a second SELECT after INSERT — 1 round trip instead of 2.
 */
export async function createUser(
  email: string,
  username: string,
  passwordHash: string | null
): Promise<UserRow> {
  const result = await pool.query<UserRow>(
    `INSERT INTO users (id, email, username, password_hash, created_at)
     VALUES (gen_random_uuid(), $1, $2, $3, NOW())
     RETURNING id, email, username, password_hash, created_at`,
    [email.toLowerCase().trim(), username.trim(), passwordHash]
  );
  return result.rows[0];
}

/**
 * Check if an email is already registered.
 * Returns true if taken — caller sends 409 Conflict before INSERT attempt.
 *
 * Belt-and-suspenders: the DB UNIQUE constraint also catches the race condition
 * where two requests call isEmailTaken() simultaneously (both get false),
 * then both try INSERT — one gets a 23505 unique violation, which we catch.
 */
export async function isEmailTaken(email: string): Promise<boolean> {
  const result = await pool.query<{ exists: boolean }>(
    `SELECT EXISTS(SELECT 1 FROM users WHERE email = $1) AS exists`,
    [email.toLowerCase().trim()]
  );
  return result.rows[0]?.exists ?? false;
}
